### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by yaroslav-hub** [orzaev12/TL-Practice#1]
В репозитории не хватает файла .gitignore. Из-за этого много лишних системных файлов запушилось.

**Comment by orzaev12** [comment]
Добавил .gitignore. На данный момент имеются лишние файлы или всё "OK"?

**Comment by yaroslav-hub** [comment]
Нет, все ненужные файлы так и остались. Чтобы их убрать, если изначально не было в первом пуше .gitignore, надо удалять вручную.
