### ISSUE TITLE
Интерфейс.

### ISSUE THREAD

**Issue by yaroslav-hub** [orzaev12/TL-Practice#4]
Зачем нужен этот интерфейс?

https://github.com/orzaev12/TL-Practice/blob/a97add3faf6fead9ef190d3d699c26d92c7175db/Homework%201/BubbleSort/BubbleSort/Program.cs#L3C58-L3C69

**Comment by orzaev12** [comment]
Данный интерфейс служит для сравнения

**Comment by orzaev12** [comment]
Вот тут хорошо описывают: https://professorweb.ru/my/csharp/charp_theory/level12/12_16.php

**Comment by orzaev12** [comment]
Определяет обобщенный метод сравнения, который реализуется типом значения или классом для упорядочения или сортировки экземпляров.

**Comment by yaroslav-hub** [comment]
Объясните своими словами, не текстом из документации.

**Comment by orzaev12** [comment]
Данный интерфейс служит для сравнения данных: поскольку, у нас входе данные типа int, т. е, которые можно отсортировать, причем они содержатся в списке, т. е объекте, то поэтому используется интерфейс IComparable<T>. Указатель <T> применяется для сортировки объектов, хранящихся в одной коллекции, что в нашем случае - список List.
Интерефейс IComparable<T> использует единственный метод CompareTo(): этим методом интерфейс IComparable и сравнивает объекты, в нашем случае - числа.
