### ISSUE TITLE
Регулярное выражение.

### ISSUE THREAD

**Issue by yaroslav-hub** [orzaev12/TL-Practice#7]
Откуда была взята регулярка?

https://github.com/orzaev12/TL-Practice/blob/a97add3faf6fead9ef190d3d699c26d92c7175db/Homework%201/Survey/Survey/Program.cs#L14C26-L14C55

**Comment by orzaev12** [comment]
Данная регулярка была взята у одногруппника.

чт, 6 июл. 2023 г., 23:39 Yaroslav ***@***.***>:

**Comment by orzaev12** [comment]
Хотел бы уточнить: если дз отправлено на доработку, то потом его нужно просто загрузить? Или необходимо отметить, что переделал и тп? Или как?

**Comment by yaroslav-hub** [comment]
Необходимо запушить изменения и написать в issue, что замечание исправлено с ссылкой на коммит. Если всё норм, я закрою issue.

**Comment by orzaev12** [comment]
Программа, собирающая информацию о человеке, слегка была переписана.
Устранен баг с неправильным выводом возраста человека.

**Comment by orzaev12** [comment]
Регулярку поменял. Взял отсюда: https://www.cyberforum.ru/csharp-beginners/thread1548643.html
