### ISSUE TITLE
Разное написание имен

### ISSUE THREAD

**Issue by AlekseiPavlovskii** [orzaev12/TL-Practice#9]
Часть имен сущностей выделена квадратными скобками, часть нет. Лучше придерживаться единообразия в коде

**Comment by orzaev12** [comment]
Это вызвано тем, что почему-то в mssql писать "order" без скобок, то он выдаёт ошибку, поэтому писал так. 
Хорошо, принял!

**Comment by orzaev12** [comment]
При попытке выделения всех имен в квадратные скобки, mssql выдает ошибку, как и если "Order" писать без квадратных скобок. Поэтому, оставил как есть.

**Comment by AlekseiPavlovskii** [comment]
Покажите ошибку при выделении всех имен. Скриншот фрагмента кода с ошибкой + текста ошибки

**Comment by orzaev12** [comment]
Исправил, все наименования таблиц занес в []. 
Ошибка была в том, что я проверял работу таблиц в [] в скрипте создания таблиц. Проблема же была в том, что я пытался создать таблицу с наименованием, которое уже существует) Поправил все скрипты.
